name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run on push to main branch
  workflow_dispatch:  # Allow manual execution

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate DOCKER_USERNAME Secret
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "ERROR: DOCKER_USERNAME secret is not set."
            exit 1
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pdfsandwich-docker:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pdfsandwich-docker:latest
